list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/screens/main_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/bonanza_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/bonanza_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/fmtowns_8x16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/portfolio_6x8_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/bitaxe_logo_data.c)